<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.*-* " />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.*-* " />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary.domian\ClassLibrary.domian.csproj" />
    <ProjectReference Include="..\ClassLibrary2\ClassLibrary2.csproj" />
    <ProjectReference Include="..\Library.services1\Library.services1.csproj" />
    <ProjectReference Include="..\Library.ServicesInterface\Library.ServicesInterface.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Components\Pages\ServiceComponents\AddEditServiceDialog.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Components\Pages\ServiceComponents\Service1.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>
</Project>
